import { describe, expect, it } from "bun:test";

import { readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { catalogKeys as readCatalogKeys } from "./helpers/catalog.js";

// ---------------------------------------------------------------------------
// BACKEND labelKey CONTRACT.
//
// The backend emits i18n keys as DATA (`labelKey`, `reasonKey`, `lostKey`,
// `recoveredKey`, `unavailableReason`, …) that the frontend resolves at render
// time. Nothing type-checks that relationship: a key renamed in the catalog, or
// a key invented in a backend module, fails only as a raw dotted string in front
// of an operator.
//
// This gate extracts every dotted key the backend source can emit and asserts it
// resolves in the `en` catalog.
//
// IT READS THE CATALOG STRUCTURE, NOT THE RUNTIME — which is why it SURVIVED the
// Paraglide migration by changing ONE function, `loadEnCatalogKeys()` below: the
// legacy nested-dictionary walk became a read of `messages/en.json`, whose keys
// are already the verbatim dotted form. Everything else stands unchanged.
// ---------------------------------------------------------------------------

const HERE = dirname(fileURLToPath(import.meta.url));
const BACKEND_SRC = join(HERE, "..", "..", "..", "apps", "backend", "src");

// ===== THE ONE MIGRATION SEAM ==============================================
/** Every dotted key of the `en` catalog. */
function loadEnCatalogKeys(): Set<string> {
	return new Set(readCatalogKeys("en"));
}
// ===========================================================================

/**
 * The catalog's top-level namespaces. A dotted string literal in backend source
 * is only a CANDIDATE i18n key when its first segment is one of these — that is
 * what keeps oRPC procedure paths (`auth.login`), systemd unit names, and
 * dotted config paths out of the candidate set without an ever-growing
 * exclusion list.
 */
function catalogNamespaces(keys: Set<string>): Set<string> {
	const namespaces = new Set<string>();
	for (const key of keys) {
		const head = key.split(".")[0];
		if (head) namespaces.add(head);
	}
	return namespaces;
}

/**
 * Dotted strings that LOOK like catalog keys but are not — each is a real
 * identifier from a different namespace that happens to collide with a catalog
 * top-level name. Every entry names its source; nothing is excluded for merely
 * failing the assertion.
 */
const NOT_I18N_KEYS = new Set<string>([
	// nmcli connection property, `modules/wifi/wifi-hotspot-config.ts` /
	// `wifi-hotspot-types.ts` — collides with the `connection.*` namespace.
	"connection.autoconnect",
	// oRPC procedure path, `rpc/adapter.ts` post-login branch — collides with
	// the `auth.*` namespace.
	"auth.login",
	// control-protocol self-fencing op name, `modules/remote-control/
	// self-fencing.ts` — collides with the `network.*` namespace.
	"network.reconfig",
]);

/**
 * `settings.sources.<id>` is generated by `sourceLabelKey(id)`
 * (`modules/streaming/sources.ts`) from an engine-reported source id, so the
 * family cannot be found by scanning for literals. These are the ids the backend
 * itself names in source — the coarse pipelines it suppresses, the two network
 * ingest kinds, the virtual test pattern — every one of which must resolve.
 */
const SOURCE_LABEL_IDS = [
	"libuvch264",
	"usb_mjpeg",
	"v4l_mjpeg",
	"camlink",
	"hdmi",
	"rtmp",
	"srt",
	"test",
] as const;

const DOTTED_LITERAL = /"([a-z][a-zA-Z0-9]*(?:\.[a-zA-Z0-9_]+)+)"/g;

function collectSourceFiles(dir: string, out: string[] = []): string[] {
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry);
		if (statSync(full).isDirectory()) {
			if (entry === "tests" || entry === "node_modules") continue;
			collectSourceFiles(full, out);
			continue;
		}
		if (!entry.endsWith(".ts")) continue;
		if (entry.endsWith(".test.ts")) continue;
		out.push(full);
	}
	return out;
}

interface Candidate {
	key: string;
	file: string;
	line: number;
}

function collectCandidates(namespaces: Set<string>): Candidate[] {
	const found: Candidate[] = [];
	for (const file of collectSourceFiles(BACKEND_SRC)) {
		const lines = readFileSync(file, "utf8").split("\n");
		lines.forEach((text, index) => {
			for (const match of text.matchAll(DOTTED_LITERAL)) {
				const key = match[1];
				if (!key) continue;
				const head = key.split(".")[0];
				if (!head || !namespaces.has(head)) continue;
				if (NOT_I18N_KEYS.has(key)) continue;
				found.push({ key, file: relative(BACKEND_SRC, file), line: index + 1 });
			}
		});
	}
	return found;
}

describe("backend labelKey contract", () => {
	const catalogKeys = loadEnCatalogKeys();
	const namespaces = catalogNamespaces(catalogKeys);
	const candidates = collectCandidates(namespaces);

	it("the en catalog loaded (an empty catalog would pass everything vacuously)", () => {
		expect(catalogKeys.size).toBeGreaterThan(1000);
	});

	it("the backend scan found emitters (an empty extraction FAILS)", () => {
		expect(candidates.length).toBeGreaterThan(20);
	});

	it("covers the four known emitter modules", () => {
		const files = new Set(candidates.map((c) => c.file));
		for (const expected of [
			"modules/streaming/audio.ts",
			"modules/streaming/sources.ts",
			"modules/streaming/lifecycle-indicators.ts",
			"modules/system/software-updates.ts",
		]) {
			expect(files).toContain(expected);
		}
	});

	it("every excluded literal is still present in backend source (no stale exclusion)", () => {
		const sources = collectSourceFiles(BACKEND_SRC).map((file) => readFileSync(file, "utf8"));
		const stale = [...NOT_I18N_KEYS].filter(
			(key) => !sources.some((text) => text.includes(`"${key}"`)),
		);
		expect(stale).toEqual([]);
	});

	it("every dotted key the backend can emit exists in the en catalog", () => {
		const missing = candidates
			.filter((c) => !catalogKeys.has(c.key))
			.map((c) => `${c.key} (${c.file}:${c.line})`)
			.sort();
		expect(missing).toEqual([]);
	});

	it("every settings.sources.<id> the backend can generate exists in the en catalog", () => {
		const missing = SOURCE_LABEL_IDS.map((id) => `settings.sources.${id}`).filter(
			(key) => !catalogKeys.has(key),
		);
		expect(missing).toEqual([]);
	});
});
