/**
 * POST-COMPILE GENERATOR — the facade's per-namespace barrels and message registry.
 *
 * WHY this exists at all: paraglide's umbrella `paraglide/messages.js` does
 * `export * from './messages/_index.js'`, and `_index.js` re-exports EVERY one of
 * the 1 472 compiled message modules eagerly. Importing it therefore pulls the
 * whole catalog into whatever chunk touches i18n — lazy loading is impossible by
 * construction. Nothing outside this generator's own output may import it; the
 * `no-umbrella-import` gate enforces that.
 *
 * What it emits (all under `generated/`, gitignored, NEVER hand-edited):
 *
 *   generated/types.d.ts             `MessageFn`, `Namespace`, `MessageKey`
 *   generated/namespaces/<ns>.js     one barrel per top-level key segment
 *   generated/namespaces/<ns>.d.ts   its declaration (so TS never opens paraglide's JS)
 *   generated/namespace-map.js|.d.ts dotted key -> { namespace, moduleId }
 *   generated/loader-config.js|.d.ts eager/lazy per namespace
 *   generated/registry.js|.d.ts      the mutable synchronous registry + `m` + `ensureNamespace`
 *
 * The `.js`/`.d.ts` pair is deliberate. `apps/frontend/tsconfig.app.json` sets
 * `checkJs: true`, so a `.ts` barrel importing paraglide's JSDoc-typed `.js`
 * would drag all 1 474 generated paraglide files into svelte-check. Declaring the
 * barrels instead keeps that boundary closed: TS resolves `./namespaces/live.js`
 * to `live.d.ts` and stops there, while Vite resolves the real `.js`.
 *
 * The registry KEYS ON THE VERBATIM DOTTED KEY. Paraglide's own exports resolve
 * `m["a.b.c"]` against nothing unless every per-message module has been imported,
 * which is exactly what the umbrella does and what we refuse to do — the registry
 * is what makes synchronous bracket access work under a namespace-scoped loader.
 */

import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { toSafeModuleId } from "./message-format.js";

const PACKAGE_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/** The compiled paraglide output this generator reads. */
export const PARAGLIDE_DIR = join(PACKAGE_ROOT, "src", "paraglide");

/** Default destination for the generated facade modules. */
export const GENERATED_DIR = join(PACKAGE_ROOT, "generated");

/**
 * Namespaces loaded lazily. EMPTY by design: every namespace ships eager, so the
 * first paint has no dictionary fetch and no flicker. Flipping a namespace to
 * lazy is a CONFIG change only — `ensureNamespace()` is already wired at the
 * destination/dialog activation points, and no call site is rewritten (proved by
 * the lazy-namespace test in apps/frontend).
 */
export const LAZY_NAMESPACES: readonly string[] = [];

export interface GenerateOptions {
	/** Where to write the generated modules. Defaults to `generated/`. */
	outDir?: string;
	/** Namespaces to load on demand. Defaults to {@link LAZY_NAMESPACES}. */
	lazyNamespaces?: readonly string[];
	/** Compiled paraglide output to read. Defaults to `src/paraglide`. */
	paraglideDir?: string;
}

export interface GenerateResult {
	outDir: string;
	namespaces: string[];
	lazyNamespaces: string[];
	keyCount: number;
}

/** Every dotted key in the base catalog, sorted, `$schema` excluded. */
function readCatalogKeys(): string[] {
	const raw = readFileSync(join(PACKAGE_ROOT, "messages", "en.json"), "utf8");
	const parsed = JSON.parse(raw) as Record<string, unknown>;
	return Object.keys(parsed)
		.filter((key) => key !== "$schema")
		.sort();
}

/** A key's namespace is its FIRST dotted segment — the unit `ensureNamespace` loads. */
export function namespaceOf(key: string): string {
	const dot = key.indexOf(".");
	return dot === -1 ? key : key.slice(0, dot);
}

const BANNER =
	"// GENERATED by packages/i18n/scripts/generate-registry.ts — DO NOT EDIT.\n";

function quote(value: string): string {
	return JSON.stringify(value);
}

function barrelSource(keys: string[], relativeToParaglide: string): string {
	const imports = keys
		.map(
			(key, index) =>
				`import * as _${index} from ${quote(`${relativeToParaglide}/messages/${toSafeModuleId(key)}.js`)};`,
		)
		.join("\n");
	const spread = keys.map((_key, index) => `\t...(_${index}),`).join("\n");
	return `${BANNER}${imports}\n\nexport const messages = {\n${spread}\n};\n`;
}

const BARREL_DECLARATION = `${BANNER}import type { MessageFn } from "../types.js";

export declare const messages: Readonly<Record<string, MessageFn>>;
`;

function typesDeclaration(namespaces: string[], keys: string[]): string {
	return `${BANNER}/**
 * A compiled paraglide message. \`inputs\` carries the message's named variables;
 * \`options.locale\` renders in an explicit locale WITHOUT touching global state.
 */
export type MessageFn = (
	inputs?: Record<string, unknown>,
	options?: { locale?: string },
) => string;

export type Namespace =
${namespaces.map((ns) => `\t| ${quote(ns)}`).join("\n")};

export type MessageKey =
${keys.map((key) => `\t| ${quote(key)}`).join("\n")};
`;
}

function namespaceMapSource(keys: string[]): string {
	const entries = keys
		.map(
			(key) =>
				`\t[${quote(key)}]: { namespace: ${quote(namespaceOf(key))}, moduleId: ${quote(toSafeModuleId(key))} },`,
		)
		.join("\n");
	return `${BANNER}/**
 * dotted key -> { namespace, paraglide safe module id }.
 *
 * The moduleId half is the lossy \`toSafeModuleId\` mapping paraglide applies when
 * it writes \`messages/<moduleId>.js\`; it is emitted here so tests can assert the
 * table against the files paraglide really produced.
 */
export const NAMESPACE_MAP = {
${entries}
};
`;
}

const NAMESPACE_MAP_DECLARATION = `${BANNER}import type { MessageKey, Namespace } from "./types.js";

export declare const NAMESPACE_MAP: Readonly<
	Record<MessageKey, { readonly namespace: Namespace; readonly moduleId: string }>
>;
`;

function loaderConfigSource(
	namespaces: string[],
	lazy: readonly string[],
): string {
	const lazySet = new Set(lazy);
	const entries = namespaces
		.map(
			(ns) =>
				`\t[${quote(ns)}]: ${quote(lazySet.has(ns) ? "lazy" : "eager")},`,
		)
		.join("\n");
	return `${BANNER}/**
 * Per-namespace loading mode. \`eager\` namespaces are registered at module init;
 * \`lazy\` ones only once \`ensureNamespace()\` resolves. Flipping a value here is
 * the WHOLE mitigation — no call site changes.
 */
export const LOADER_CONFIG = {
${entries}
};

export const EAGER_NAMESPACES = ${JSON.stringify(namespaces.filter((ns) => !lazySet.has(ns)))};

export const LAZY_NAMESPACES = ${JSON.stringify(namespaces.filter((ns) => lazySet.has(ns)))};
`;
}

const LOADER_CONFIG_DECLARATION = `${BANNER}import type { Namespace } from "./types.js";

export declare const LOADER_CONFIG: Readonly<Record<Namespace, "eager" | "lazy">>;
export declare const EAGER_NAMESPACES: readonly Namespace[];
export declare const LAZY_NAMESPACES: readonly Namespace[];
`;

function registrySource(
	namespaces: string[],
	lazy: readonly string[],
): string {
	const lazySet = new Set(lazy);
	const eager = namespaces.filter((ns) => !lazySet.has(ns));
	const lazyOnly = namespaces.filter((ns) => lazySet.has(ns));

	const eagerImports = eager
		.map((ns, index) => `import * as _ns${index} from "./namespaces/${ns}.js";`)
		.join("\n");
	const eagerRegistrations = eager
		.map((ns, index) => `registerNamespace(${quote(ns)}, _ns${index}.messages);`)
		.join("\n");
	// A STATIC map of thunks, not `import(\`./namespaces/${ns}.js\`)` — a template
	// literal specifier makes the bundler emit every namespace as a candidate
	// chunk of one glob, which is exactly the eager collapse we are avoiding.
	const lazyLoaders = lazyOnly
		.map((ns) => `\t[${quote(ns)}]: () => import("./namespaces/${ns}.js"),`)
		.join("\n");

	return `${BANNER}import { LOADER_CONFIG } from "./loader-config.js";
import { NAMESPACE_MAP } from "./namespace-map.js";
${eagerImports}

const registry = new Map();
const loaded = new Set();

function registerNamespace(namespace, messages) {
	for (const key of Object.keys(messages)) {
		registry.set(key, messages[key]);
	}
	loaded.add(namespace);
}

${eagerRegistrations}

const LAZY_LOADERS = {
${lazyLoaders}
};

/** The namespace a dotted key belongs to, or undefined for an unknown key. */
export function namespaceForKey(key) {
	return NAMESPACE_MAP[key]?.namespace;
}

/** Whether a namespace's messages are in the registry right now. */
export function isNamespaceLoaded(namespace) {
	return loaded.has(namespace);
}

/**
 * Load a namespace's messages into the registry. Eager namespaces resolve
 * immediately (they were registered at module init); a lazy one resolves once
 * its chunk has been fetched. Call it BEFORE rendering the view that consumes
 * the namespace — after it resolves, every \`m["ns.key"]()\` in that view is a
 * plain synchronous call, unchanged from the eager configuration.
 */
export async function ensureNamespace(namespace) {
	if (loaded.has(namespace)) return;
	const load = LAZY_LOADERS[namespace];
	if (load === undefined) {
		throw new Error(\`Unknown i18n namespace: \${namespace}\`);
	}
	const mod = await load();
	registerNamespace(namespace, mod.messages);
}

/** Every namespace the catalog defines. */
export const NAMESPACES = ${JSON.stringify(namespaces)};

/** Raw registry read. \`undefined\` for an unknown or not-yet-loaded key. */
export function getMessage(key) {
	return registry.get(key);
}

/**
 * The facade's message accessor. Bracket access on the VERBATIM dotted key:
 * \`m["live.setup.title"]()\`. An unknown or not-yet-loaded key returns a
 * function that echoes the key back, which is byte-identical to the legacy
 * proxy's miss behaviour.
 */
export const m = new Proxy(Object.create(null), {
	get(_target, key) {
		if (typeof key !== "string") return undefined;
		return registry.get(key) ?? (() => key);
	},
	has(_target, key) {
		return typeof key === "string" && registry.has(key);
	},
	ownKeys() {
		return [...registry.keys()];
	},
	getOwnPropertyDescriptor(_target, key) {
		if (typeof key !== "string" || !registry.has(key)) return undefined;
		return { enumerable: true, configurable: true, value: registry.get(key) };
	},
});

/**
 * Dynamic dotted-key resolution for the call sites that hold a key in a variable
 * (backend-emitted \`labelKey\`/\`reasonKey\` values). Fallback semantics are the
 * legacy resolver's, byte for byte: an unknown key is RETURNED AS ITSELF, never
 * thrown and never rendered as empty.
 */
export function resolveMessageKey(key, params) {
	const message = registry.get(key);
	if (message === undefined) return key;
	return message(params);
}

/** Loading mode per namespace — re-exported so consumers need one import. */
export { LOADER_CONFIG };
`;
}

/**
 * A narrow re-export of the paraglide runtime. It exists so the facade never
 * imports paraglide's JSDoc-typed `.js` directly: with `checkJs: true` in the
 * frontend tsconfig that would pull the whole generated runtime into
 * svelte-check. The `.d.ts` beside it closes the boundary.
 */
function runtimeShimSource(relativeToParaglide: string): string {
	return `${BANNER}export {
	baseLocale,
	getLocale,
	isLocale,
	locales,
	setLocale,
} from ${quote(`${relativeToParaglide}/runtime.js`)};
`;
}

const RUNTIME_SHIM_DECLARATION = `${BANNER}export declare const baseLocale: string;
export declare const locales: readonly string[];
export declare function getLocale(): string;
export declare function isLocale(value: unknown): boolean;
export declare function setLocale(
	locale: string,
	options?: { reload?: boolean },
): void;
`;

const REGISTRY_DECLARATION = `${BANNER}import type { MessageFn, MessageKey, Namespace } from "./types.js";

export type { MessageFn, MessageKey, Namespace } from "./types.js";

export declare function namespaceForKey(key: string): Namespace | undefined;
export declare function isNamespaceLoaded(namespace: Namespace): boolean;
export declare function ensureNamespace(namespace: Namespace): Promise<void>;
export declare function getMessage(key: string): MessageFn | undefined;
export declare const NAMESPACES: readonly Namespace[];
export declare const LOADER_CONFIG: Readonly<Record<Namespace, "eager" | "lazy">>;

/**
 * Bracket access on the verbatim dotted key. Typed keys are known statically;
 * a \`string\` index is still allowed for the dynamic call sites, and resolves
 * through the same miss-returns-the-key rule.
 */
export declare const m: Readonly<Record<MessageKey, MessageFn>> &
	Readonly<Record<string, MessageFn>>;

export declare function resolveMessageKey(
	key: string,
	params?: Record<string, unknown>,
): string;
`;

export function generateRegistry(options: GenerateOptions = {}): GenerateResult {
	const outDir = options.outDir ?? GENERATED_DIR;
	const paraglideDir = options.paraglideDir ?? PARAGLIDE_DIR;
	const lazy = options.lazyNamespaces ?? LAZY_NAMESPACES;

	const keys = readCatalogKeys();
	const byNamespace = new Map<string, string[]>();
	for (const key of keys) {
		const ns = namespaceOf(key);
		const bucket = byNamespace.get(ns);
		if (bucket === undefined) byNamespace.set(ns, [key]);
		else bucket.push(key);
	}
	const namespaces = [...byNamespace.keys()].sort();

	for (const ns of lazy) {
		if (!byNamespace.has(ns)) {
			throw new Error(`Lazy namespace ${quote(ns)} is not in the catalog.`);
		}
	}

	rmSync(outDir, { recursive: true, force: true });
	mkdirSync(join(outDir, "namespaces"), { recursive: true });

	// Relative specifier from generated/namespaces/<ns>.js to the paraglide output.
	const relativeToParaglide = relativeSpecifier(
		join(outDir, "namespaces"),
		paraglideDir,
	);

	for (const ns of namespaces) {
		const nsKeys = byNamespace.get(ns) ?? [];
		writeFileSync(
			join(outDir, "namespaces", `${ns}.js`),
			barrelSource(nsKeys, relativeToParaglide),
		);
		writeFileSync(join(outDir, "namespaces", `${ns}.d.ts`), BARREL_DECLARATION);
	}

	writeFileSync(
		join(outDir, "runtime.js"),
		runtimeShimSource(relativeSpecifier(outDir, paraglideDir)),
	);
	writeFileSync(join(outDir, "runtime.d.ts"), RUNTIME_SHIM_DECLARATION);
	writeFileSync(join(outDir, "types.d.ts"), typesDeclaration(namespaces, keys));
	writeFileSync(join(outDir, "namespace-map.js"), namespaceMapSource(keys));
	writeFileSync(join(outDir, "namespace-map.d.ts"), NAMESPACE_MAP_DECLARATION);
	writeFileSync(
		join(outDir, "loader-config.js"),
		loaderConfigSource(namespaces, lazy),
	);
	writeFileSync(join(outDir, "loader-config.d.ts"), LOADER_CONFIG_DECLARATION);
	writeFileSync(join(outDir, "registry.js"), registrySource(namespaces, lazy));
	writeFileSync(join(outDir, "registry.d.ts"), REGISTRY_DECLARATION);

	// Bundler-facing sidecar. `manualChunks` is synchronous and runs in the Vite
	// config's own module scope, so it cannot `await import()` the ESM loader
	// config — it reads this instead to answer "which namespace owns this
	// compiled message module, and is that namespace eager?".
	const lazySet = new Set(lazy);
	writeFileSync(
		join(outDir, "chunk-plan.json"),
		`${JSON.stringify(
			{
				loading: Object.fromEntries(
					namespaces.map((ns) => [ns, lazySet.has(ns) ? "lazy" : "eager"]),
				),
				moduleNamespaces: Object.fromEntries(
					keys.map((key) => [toSafeModuleId(key), namespaceOf(key)]),
				),
			},
			null,
			"\t",
		)}\n`,
	);

	return {
		outDir,
		namespaces,
		lazyNamespaces: namespaces.filter((ns) => lazy.includes(ns)),
		keyCount: keys.length,
	};
}

/** POSIX-style relative module specifier from `from` to `to`. */
function relativeSpecifier(from: string, to: string): string {
	const fromParts = from.split(/[/\\]/).filter(Boolean);
	const toParts = to.split(/[/\\]/).filter(Boolean);
	let shared = 0;
	while (
		shared < fromParts.length &&
		shared < toParts.length &&
		fromParts[shared] === toParts[shared]
	) {
		shared += 1;
	}
	const up = Array<string>(fromParts.length - shared).fill("..");
	const down = toParts.slice(shared);
	return [...up, ...down].join("/") || ".";
}

if (import.meta.main) {
	const result = generateRegistry();
	process.stdout.write(
		`generated ${result.namespaces.length} namespace barrels (${result.keyCount} keys, ` +
			`${result.lazyNamespaces.length} lazy) to ${result.outDir}\n`,
	);
}
