name: i18n Validation

on:
  pull_request:
    paths:
      - 'src/locale/**'
      - 'src/**/*.svelte'
      - 'src/**/*.ts'
      - 'src/**/*.js'
  push:
    branches: [main, develop]
    paths:
      - 'src/locale/**'

jobs:
  validate-i18n:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        
    - name: Install pnpm
      run: corepack enable && corepack prepare pnpm@latest --activate
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Run i18n validation
      run: npm run i18n:validate
      
    - name: Check for potential cleanup opportunities
      run: npm run i18n:cleanup-dry
      continue-on-error: true
      
    - name: Comment on PR if issues found
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ i18n validation failed. Please run `npm run i18n:check` locally and fix any issues.'
          });